_BASE_: "Base-CRCNN-COCO.yaml"
MODEL:
  META_ARCHITECTURE: "SplitClassifierRCNN"
  ROI_HEADS:
    NUM_CLASSES: -1
    NAME: "MultiDatasetCascadeROIHeads"
  ROI_BOX_HEAD:
    USE_SIGMOID_CE: True
    # USE_EQL_LOSS: True
    HIERARCHY_IGNORE: True
    HIERARCHY_POS_PARENTS: True
DATASETS:
  TRAIN: ("test_train","widerface_train")
  TEST: ('test_val','widerface_val')
DATALOADER:                                                                                                                                                                                                                                                                                                                                                                 
  SAMPLER_TRAIN: "MultiDatasetSampler"
  NUM_WORKERS: 1
MULTI_DATASET:
  ENABLED: True
  DATASETS: ['test', 'widerface',]
  NUM_CLASSES: [6, 1,]
  DATA_RATIO: [1, 1,]
  USE_CAS: [False, False,]
SOLVER:
  IMS_PER_BATCH: 64
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  CHECKPOINT_PERIOD: 1000

